### ISSUE TITLE
sd not defined in this scope

### ISSUE THREAD

**Issue by huskeyw** [MockbaTheBorg/RunCPM#106]
compiling for DUO and get SD not defined in this scope

**Comment by huskeyw** [comment]
fixed, switched to the adafruit lib version of sdfat..

**Comment by MockbaTheBorg** [comment]
This problem had been seen before, you need to make a small modification to greiman's sdfat config.

**Comment by huskeyw** [comment]
no it was the wrong sdfat from library manager.. needed the adafruit one..
then everything worked. the changes were already there when installed.
thanks for looking into it thought..

to be clear there are two sdfat libraries and had to install the adafruit
one instead of the standard sdfat
William "Steve" Huskey
Managing Member Dreadnought Brewing LLC

**Comment by MockbaTheBorg** [comment]
Awesome. 
I originally used Bill Greiman's library because of its higher speed and compatibility with all systems, and I see now there's an Adafruit fork of it.
Glad to know it is working for you. Have fun, and feel free to join us on the Discord channel if you want.

Cheers!!!
Marcelo.
