### ISSUE TITLE
RX0 (serial port0) issue with RunCPM on Arduino Due

### ISSUE THREAD

**Issue by guidol70** [MockbaTheBorg/RunCPM#117]
As **Information/Solution** for other users of RunCPM on the Arduino Due:

There is a hardware-design-error on some Clones and some Revisions of the original 
Arduino Due which prevents the correct use of the RX0-Pin (serial TTL-Port Receive-Pin)
while not using the USB-Programming-Port for accessing RunCPM on the Arduino Due.
See [RX pin doesn't work](https://forum.arduino.cc/index.php?topic=474483.0)

The solution is to **use the serial port 1** = RX1 and TX1

For that you have to replace all occurrences of "**Serial.**" with "**Serial1.**"

After compiling/uploading the sketch RunCPM on the Arduno Due will work with projects like

[PiGFX](https://github.com/fbergama/pigfx) (Raspberry Pi as serial Terminal using USB-Keyboard)

and 
[ESPTerm](https://github.com/espterm/espterm-firmware) (ESP8266):

see also (in german) the [problem-description](https://forum.classic-computing.de/forum/index.php?thread/21251-pigfx-1-8-0-und-serial-rx0-problem-des-arduino-due-runcpm/)

**Comment by MockbaTheBorg** [comment]
Updated and referenced on the Readme.
