### ISSUE TITLE
After "internal CCP" reset/reload MBASIC doesnt load again

### ISSUE THREAD

**Issue by guidol70** [MockbaTheBorg/RunCPM#126]
Maybe a issue after the last internal CCP correction? - because in RunCPM v5.2 it did work to load MBASIC again after leaving it with "system" as exit command.

With v5.4 from today I got this problem :( on Win and VGA32 (ESP32)
![RunCPM_v5_4_internal_CCP_reset_problem_VGA32](https://user-images.githubusercontent.com/5121124/116707962-e92c7600-a9d7-11eb-93d9-3c85da2bb1e2.jpg)
![RunCPM_v5_4_internal_CCP_reset_problem_Win](https://user-images.githubusercontent.com/5121124/116707965-ea5da300-a9d7-11eb-87e0-2031d04d1655.jpg)

With v5.3 I got a debug-ouput at the end of the void setup of the .ino which is displayed in v5.3 (so the terminal did close?) but in v5.4 this isnt shown anymore :(

![RunCPM_v5_3_internal_CCP_reset_problem_VGA32](https://user-images.githubusercontent.com/5121124/116710020-f5b1ce00-a9d9-11eb-9c29-0bfbabe7db4f.jpg)

Wordstar has also a problem with v5.4 :(

![RunCPM_v5_4_internal_CCP_reset_problem_Wordstar_VGA32](https://user-images.githubusercontent.com/5121124/116711879-f21f4680-a9db-11eb-8c62-a9ac92743268.jpg)

**Comment by guidol70** [comment]
seems to be the CCP change from 3 days ago :(
fixed .ARK/UNARC, but I dont know wher could be the problem

**Comment by MockbaTheBorg** [comment]
Please check again ... the latest v5.4 should have fixed it.

**Comment by Waffle2** [comment]
It would appear that you have fixed it.  This was a problem for me as well, using m80/l80 and ddt.  The latest code indeed seems to solve it.  Thank you very much for the great environment, as well!
