### ISSUE TITLE
[Info] Discord Invite Link doesnt work anymore

### ISSUE THREAD

**Issue by guidol70** [MockbaTheBorg/RunCPM#137]
Some people did tell me that they cant use the Discord Invite Link anymore, because its no more space for more users?

Can you please check this?
Thanks in advance :)

**Comment by MockbaTheBorg** [comment]
A friend of mine just joined. No issues.
And I saw people also joined recently, so I am not sure what the issue would be.
They would need to get us screenshots of the issue. Maybe they are on too many groups (there's a limit of groups you can be on).

**Comment by MockbaTheBorg** [comment]
I will close for now ... we let people reopen (or open a new one) once they have a screenshot of the error message.
