### ISSUE TITLE
MacOS X Wordstar - Arrow Keys

### ISSUE THREAD

**Issue by snakebyte69** [MockbaTheBorg/RunCPM#139]
Does anyone have a solution to get the arrow keys on a Mac Laptop to work inside Wordstar?

e.g. CTRL+SHIFT+ALT+F6 - VT100 Arrow Keys (Doesn't work on the Mac)

**Comment by MockbaTheBorg** [comment]
Hi @snakebyte69,

This also happens on Windows. 
The "official" arrow keys on Wordstar are actually ^S, ^D, ^E and ^X.
Anything other than that is terminal specific and should be implemented (if possible) by using the WINSTALL or WSCHANGE application to match the keys your terminal emulator on the Mac sends. As it was done back in the CP/M days.

Maybe some folk at the discord group could help with that, as there might be other Mac users there.
https://discord.gg/WTTWVZ6

Closing as not actually a RunCPM issue.
