### ISSUE TITLE
VT340 feature request

### ISSUE THREAD

**Issue by snakebyte69** [MockbaTheBorg/RunCPM#140]
How about expanding the terminal capability from VT-100 to VT-340 for more graphic capabilities using Digital ReGIS and SIXEL graphics. You can emulated a VT-340 with xterm : xterm -ti 340

**Comment by drawkula** [comment]
...like this?

![20211204-230404__sixel_mandelbrot](https://user-images.githubusercontent.com/9768622/144727294-4d90f7b9-6283-4334-b977-e291c7cb5d2c.png)

[MB6EL.ZIP](https://github.com/MockbaTheBorg/RunCPM/files/7654885/MB6EL.ZIP)

**Comment by snakebyte69** [comment]
How are you running that?

**Comment by drawkula** [comment]
I'm using an XTerm with enabled VT340 features.  My `~/.Xresources` contains:
```
!! for SIXELS
!!
XTerm*decTerminalID: vt340
XTerm*numColorRegisters: 256
```

**Comment by snakebyte69** [comment]
Have you tried it on a Mac?

**Comment by drawkula** [comment]
No Apple stuff here, except the ones that really grow on trees.

**Comment by drawkula** [comment]
Related:
—▷ https://github.com/MockbaTheBorg/RunCPM/issues/141

**Comment by MockbaTheBorg** [comment]
Yes ... this is a terminal capability "issue", not RunCPM capability. There's nothing for RunCPM to do here. I will close as it is (technically) already implemented.
