### ISSUE TITLE
Programmable Character Graphics

### ISSUE THREAD

**Issue by snakebyte69** [MockbaTheBorg/RunCPM#141]
How about user specified fonts allowing for programmable characters so PETSCII graphics and systems like the Microbee could be emulated. A font for Mac/Windows could be created with PCG characters that match what is running on the target machine. CP/M development could be done running under RunCPM modified for the target machine when finished.

Unicode would allow for standard ASCII characters and programmable fonts which could be specified in basic or assembler e.g. CHR$(200) or $1B,"200"

PETSCII can be achieved by using 2 characters to achieve a 16x16 square character.

**Comment by drawkula** [comment]
Why?

CP/M systems are not bound to one terminal type.  Serious CP/M software ™should be™ configurable for a variety of terminal types.

RunCPM does not include the terminal emulation.  It just communicates to an external terminal.

Unicode?

That'd be sloooooow.  How would you fit the bitmaps of tens of thousands of characters into a 64kByte system?  The character definitions would need to be on the mass storage instead.

Emulations for systems with only one terminal type with graphics (like Sinclair Spectrum) may fit these ideas (except Unicode) better.

**Comment by guidol70** [comment]
> Why?
> 
> CP/M systems are not bound to one terminal type. Serious CP/M software ™should be™ configurable for a variety of terminal types.
> 
> RunCPM does not include the terminal emulation. It just talks to an external terminal.
> 

but you can configure puTTY to use a C64 PETSCII-TrueType-Font ;)

![RunCPM_PETSCII](https://user-images.githubusercontent.com/5121124/145075406-2c93be85-c378-4bba-81db-7fd05ef956ab.jpg)

**Comment by drawkula** [comment]
That does not contradict what I wrote.
It even underlines it!
You changed the font the terminal(-emulator-program) uses, not something in RunCPM.

**Comment by MockbaTheBorg** [comment]
But what I understood from @snakebyte69 is that he is thinking about a custom made TTF font to use on the terminal emulator (Windows, Linux or Mac) to emulate those systems. Not adding a font support to RunCPM, am I correct?

**Comment by snakebyte69** [comment]
> But what I understood from @snakebyte69 is that he is thinking about a custom made TTF font to use on the terminal emulator (Windows, Linux or Mac) to emulate those systems. Not adding a font support to RunCPM, am I correct?

Yes. Commodore PET is PCG only, Microbee has PCG capability. It's not about speed it's about developing for old 8 bit systems using a Mac Laptop (in my case) and tools. Sublime Text, Cross Compilers, RunCPM, fonts as a substitute for PCG characters.

**Comment by MockbaTheBorg** [comment]
I think this one is settled as we have established that the font support should be a functionality of the terminal server (or terminal emulator) being used.
