### ISSUE TITLE
ncurses.h not found in download

### ISSUE THREAD

**Issue by cdhdds** [MockbaTheBorg/RunCPM#146]
Tried to build RunCPM on Ubuntu linux, error, No File ncurses.h.  I did a search of entire folder and subfolders and file by that name not found.

**Comment by MockbaTheBorg** [comment]
This is described in the GitHub readme page. 
I will put a comment there recommending folks to read it fully before building.

**Comment by cdhdds** [comment]
Sorry, guilty!
