### ISSUE TITLE
[Question] MBASIC and TPA Size 60K <-> 64K

### ISSUE THREAD

**Issue by guidol70** [MockbaTheBorg/RunCPM#164]
Just a short question:
on
http://stjarnhimlen.se/apple2/Apple.CPM.ref.txt
is written that MBASIC defaults to use "all TPA" memory (Highest memory location):
```
MBASIC/GBASIC  [/filename] [/F:<no_files>] [/M:<max_mem>] [/S:<max_recsize>]
    /M:<max_mem>     Highest mem location used by MBASIC (default all TPA)
```
but with a TPA-Size (configures in globals.h) of 60K or 64K I do get the same free memory size in MBASIC :(

```
RunCPM [v6.0] => CCP:[INTERNAL v3.0] TPA:[60K]
or
RunCPM [v6.0] => CCP:[INTERNAL v3.0] TPA:[64K]

A0>mbas529p
BASIC-80 Rev. 5.29
[CP/M Version]
Copyright 1985-1986 (C) by Microsoft
Created: 28-Jul-85
39224 Bytes free
Ok

```

Do think thats OK  - or TPA-Size at 64K doenst work right?
Whats the highest mem location of RunCOM at 64K TPA-Size to use the /M: Parameter?

**Comment by MockbaTheBorg** [comment]
This is normal on the internal CCP. You should see differences only on the other CCPs.
The internal CCP doesn't exist in CP/M memory, so it frees all that it can free.
