### ISSUE TITLE
[Info] Flashing LED waiting for serial connect

### ISSUE THREAD

**Issue by guidol70** [MockbaTheBorg/RunCPM#165]
On Arduinos or some CDC-USB-serial port the normal (in th original source) used code is used to blink while waiting for a serial connect to RunCPM:
```
  while (!Serial1) {	// Wait until serial is connected
    digitalWrite(LED, HIGH^LEDinv);
    delay(sDELAY);
    digitalWrite(LED, LOW^LEDinv);
    delay(DELAY);
  }
```

Because the while (!Serial1)  isnt supprted on all board I had to create a working one like the "Press space bar" message on a RC2014 board to get the Startup-Messages shown on the screen - because if the connection doesnt buffer it you will end with no or garbled startup-messages :( like I had on a ESP32-C3 or a RPi Pico which is connected to a Telnet-Server (WiFiModem from dhandel).
On the ESP32-C3 it also doenst work with the CDC-USB-serial-port to wait for the connection.

Here the source of my solution:

```
// =========================================================================================
// Wait for # keypress to show-up the Startup-Messages
// =========================================================================================

  int bootup_press = 0;
  int bootup_byte  = 0;
  int bootup_led   = 0;

  _clrscr();
  Serial1.flush();
  
  while (bootup_press == 0)
    {
      if (Serial1.available() > 0)
        { bootup_byte = Serial1.read();
            if (bootup_byte == 35) // ASCII-Code 35 = #
               {bootup_press = 1;}
        }
        
    _clrscr();
    _puts("Press the \e[1m#\e[0m key to \e[1mbootup\e[0m RunCPM :)\r\n");

    if (bootup_led == 0) {bootup_led = 1 ; digitalWrite(LED, HIGH^LEDinv);}
        else             {bootup_led = 0 ; digitalWrite(LED, LOW^LEDinv); }
    
    delay(250);
    }
  Serial1.flush();
// =========================================================================================

```

So maybe this is useful for anyone else  :)

**Comment by MockbaTheBorg** [comment]
Hi @guidol70 I suggest you post this on the Discord as well.
I will close this one so it doesn't startle me ... lol.
