### ISSUE TITLE
Allow RunCPM to be used as a Github Action for SUBMIT jobs.

### ISSUE THREAD

**Issue by ravn** [MockbaTheBorg/RunCPM#170]
I have this ancient hobby project where I disassembled the BIOS on my 8" machine to put in more stuff, and in 2021 got the bits of the old diskettes, and have used RunCPM on my Mac to replicate my toolchain back then.

I now would like to leverage Docker and Github Actions to automate this.  The tricky part was getting a command line into RunCPM but this can be done by generating A/0/$$$.SUB.

**Comment by ravn** [comment]
I was expecting I could assign myself, but apparently not :-/  This is a placeholder, not a bug report.

**Comment by MockbaTheBorg** [comment]
I have assigned you ... though at this point I believe it is already resolved?

**Comment by ravn** [comment]
Getting there.  I want to be able to transparently use this as an action, so more work is needed.

**Comment by MockbaTheBorg** [comment]
Cool ... I will close this thread so I don't get scared when I open the main page ... lol.
Then we continua to use it to report success, even closed.
Or the Discord channel.
