### ISSUE TITLE
CCP-ZCP3.60K

### ISSUE THREAD

**Issue by kenmartin-unix** [MockbaTheBorg/RunCPM#174]
I accidentally removed CCP-ZCP3.60K from RunCPM/Bin and it still works fine?

Is:

BIOS at 0xfe00 - BDOS at 0xfd00
CCP INTERNAL v3.0 at 0xfd00

RunCPM Version 6.0 (CP/M 60K)

Hard coded into RunCPM?

What is the purpose of the other CCP files?

Thanks

**Comment by MockbaTheBorg** [comment]
By default RunCPM runs on the internal CCP, which is written in C and embedded onto the code.
The other CCPs are provided for historical reasons, if you want to run on a native CCP.
All you need to do is uncomment the CCP you want and recompile (then the CCP file needs to be available on the RunCPM folder).
The whole process is described on RunCPM's readme.
