### ISSUE TITLE
Bdos Err on M: Select when I try ASM DUMP.ASM

### ISSUE THREAD

**Issue by tkurtbond** [MockbaTheBorg/RunCPM#179]
```
A0>ASM DUMP.ASM
CP/M ASSEMBLER - VER 2.0

Bdos Err on M: Select
```
Any ideas what's going wrong?

**Comment by agn453** [comment]
Check the documentation for the transient commands.

The CP/M ASM assembler takes its options from the file type parameter.

ASM FILENAME.ABC

assembles the source FILENAME.ASM on drive A:,  Producing an Intel HEX file output to B: and printer listing to drive C:

To suppress an output file use the letter Z and an X sends the listing to the console.

Tony

**Comment by tkurtbond** [comment]
Thanks!  As you can tell, I'm just getting started with CP/M and 8080/Z80 programming!
