### ISSUE TITLE
Request: Simple variation on LED.BAS as a Hello World using BDOS 9

### ISSUE THREAD

**Issue by snakebyte69** [MockbaTheBorg/RunCPM#182]
100 REM ;### BDOS procedures in machine code ###
110 REM
120 REM ;Compiles with pasmo, rasm, sjasmplus, spasm-ng, 
130 REM ;not with z80asm, not z88dk-z80asm, zasm, zmac
140 REM 
150 REM .Z80
160 REM 
170 REM WRITESTR:   EQU 9h
180 REM BDOS:       EQU 5h
190 REM 
200 REM             ORG 100h
210 REM             LD C,WRITESTR ;110D01
220 REM             LD DE,HELLO ;0E09
230 REM             CALL BDOS ;CD0500
240 REM             RST 0
250 REM 
260 REM HELLO:
270 REM             DB "Hello World!$"
280 REM    
290 REM             END ;z88dk-z80asm won't compile comment out
300 REM
310 REM **** Decimal Equivalent of Hex Opcodes ****
320 REM  0e,09,11,09,01,cd,05,00,c7,48,65,6c6c,6f,20,57,6f,72,6c,64,21,24, 
330 DATA 14,9,17,9,1,205,5,0,205,72,101,108,108,111,32,87,111,114,108,100,33,36,
340 DATA -1
350 REM
360 REM ### Load machine code procedures to memory ###
370 REM
380 BD$="" : READ A : WHILE A>-1 : BD$=BD$+CHR$(A) : READ A : WEND
390 ADR=PEEK(VARPTR(BD$)+1)+PEEK(VARPTR(BD$)+2)*256
400 REM
410 REM ### USRx = BDOS CALL 22x ###
420 REM
430 DEF USR0=ADR : DEF USR1=ADR+14 : DEF USR2=ADR+37 : DEF USR3=ADR+51
440 REM
450 REM ### Input PIN number and its value (0 = LOW, 1 = HIGH) ###
460 POKE ADR+74,P : POKE ADR+75,V

**Comment by snakebyte69** [comment]
Got it to spit junk on the screen and crash

**Comment by MockbaTheBorg** [comment]
Hi there @snakebyte69 ,

Sorry to be so late in replying.
Any progress here? I am not sure what the problem is.
The program seems to load a small assembly in memory, to print "Hello World" so it is not printing anything?

Thanks,
Marcelo.

**Comment by snakebyte69** [comment]
I was experimenting with inline assembly using BBC Basic and Microsoft Basic.
I got it working in both it doesn't use this method I created a new one.
I worked out the correct calls for BDOS and BIOS from Basic too.
