### ISSUE TITLE
8085 and APU/FPU

### ISSUE THREAD

**Issue by Torinde** [MockbaTheBorg/RunCPM#192]
Will you add emulation for 8085 and [8231/8232](https://en.wikipedia.org/wiki/Intel_8231/8232) APU/FPU chips?

**Comment by feilipu** [comment]
Just for reference, in case you want to add the Am9511A (i8231) APU, z88dk-ticks has an implementation [here](https://github.com/z88dk/z88dk/blob/master/src/ticks/am9511.c).

**Comment by MockbaTheBorg** [comment]
Sorry, no 8080/8085/8086/68000. RunCPM is Z80 only.

**Comment by feilipu** [comment]
Just FYI, we (for [RC2014](https://www.tindie.com/products/feilipu/am9511a-apu-module-pcb/) and for [z88dk](https://github.com/z88dk/z88dk/tree/master/libsrc/_DEVELOPMENT/math/float/am9511)) run / support Am9511A APU with Z80.
