### ISSUE TITLE
NZCOM

### ISSUE THREAD

**Issue by CPMArchives** [MockbaTheBorg/RunCPM#201]
Is it possible to get NZ-COM running under RunCPM?

**Comment by MockbaTheBorg** [comment]
I do not think it is possible.
NZCOM seems to path multiple CCP/BDOS/BIOS entries, which seems to fail as RunCPM is not really emulating a physical machine but translating BIOS/BDOS calls into the native operating system correspondents.
I have tried it, it fails miserably, and unless someone can verify why I would assume it is just incompatible.
