### ISSUE TITLE
make -f Makefile.posix run

### ISSUE THREAD

**Issue by drawkula** [MockbaTheBorg/RunCPM#32]
```
$ make -f Makefile.posix run
rm -f RunCPM
rm -f main.o
gcc -Wall -O0 -fPIC -Wno-unused-variable -c main.c
gcc main.o -o RunCPM -lncurses
RunCPM
make: RunCPM: Command not found
Makefile.posix:51: recipe for target 'run' failed
make: *** [run] Error 127
$ tail -2 Makefile.posix 
run: all
        $(PROG)
```
Executing `$(PROG)` will not work unless you include `.` in your `PATH` which is a big nono in the unix universe.

...and probably the sources directory does not have the CCP and the CP/M drives subdirectories, so `make run` does not make much sense for 99,593% of all RunCPM users...
o;-)

Drop the "run:" target until somewhen there is "install:" too?

**Comment by MockbaTheBorg** [comment]
Indeed... the run: target doesn't make sense, as we normally move RunCPM outside of the source directory anyways to run it.
I can attest that at least 66.6% of the users do it.

Changed and closed.
