### ISSUE TITLE
make make detect changes in headers and the Makefile itself...

### ISSUE THREAD

**Issue by drawkula** [MockbaTheBorg/RunCPM#33]
```
# Link the program
$(PROG): $(OBJS)
        $(LD) $(OBJS) -o $(PROG) $(LDFLAGS)
```
`$(PROG):` only depends on `$(OBJS)` which is the only C source of this project.
Changes to headers or the Makefile itself will not trigger a rebuild.

Adding `$(wildcard *.h) Makefile.posix` will be just a bit too active and trigger a rebuild even if a header for a different platform has changed, but I think that's tolerable. And it catches all headers by wildcard and so never adding a header to the Makefile can be forgotten.

...and later:
```
# Compile everything.
all: clean $(PROG)
```
I think a forced "make clean" before remake is not needed when the above change detects changed Makefile, C source and headers...

**Comment by MockbaTheBorg** [comment]
Done .. please run some tests.
