### ISSUE TITLE
Unable to load CP/M CCP. CPU halted.

### ISSUE THREAD

**Issue by leonardoelias300** [MockbaTheBorg/RunCPM#51]
Hello. I'm trying to run it on a teensy 3.5 but without success.
I change the SD type, A folder, 0 subfolder... there's something I'm missing?

**Comment by MockbaTheBorg** [comment]
Hi Leonardo,

To run on the Teensy you have to:

1. Format the SD card as FAT32
2. Create a "A" (uppercase, to be sure) folder on that SD card
3. Create a "0" (zero) folder inside that "A" folder
4. Copy contents of the distribuition disk (A.zip) inside that folder (optional)
5. Copy the CCP file that you intend to use onto the SD root folder (you can copy them all)

This should do it.
Please let me know if you have tried this.

Thanks,
Marcelo.

**Comment by MockbaTheBorg** [comment]
This is how my folder looks like:


![explorer_2018-04-12_17-54-35](https://user-images.githubusercontent.com/16762507/38706299-a92ef440-3e7a-11e8-98a9-90dd61c26066.png)

**Comment by leonardoelias300** [comment]
Thank you! Now its working fine... I forget to copy the CCP files to root folder! Now I'll explore!!! :)
