### ISSUE TITLE
MLOAD v2.1 has CCP 6 byte overwrite bug.

### ISSUE THREAD

**Issue by feilipu** [MockbaTheBorg/RunCPM#57]
MLOAD v2.1 has a bug where it will overwrite the first six bytes of the CCP.
Normally this is not a problem, unless the CCP is not rewritten following a warm boot.

MLOAD v2.5 fixes this problem.
See the version notes in the [mload.asm](https://github.com/MockbaTheBorg/RunCPM/files/2281422/mload.asm.txt)

Since z80.eu is down, the wayback machine has the [required zip file](https://web.archive.org/web/20160324040409/http://z80.eu/downloads/kercpm80.zip).

**Comment by MockbaTheBorg** [comment]
Thanks for pointing out. I have replaced the executable on the distribution with version 2.5.
