### ISSUE TITLE
.gitignore += more non source files

### ISSUE THREAD

**Issue by drawkula** [MockbaTheBorg/RunCPM#63]
After building (`make posix build`) several files not registered with git show up in `git status` and in the comments on each commit. They are `RunCPM`, `main.o`, `lua/lua`, `lua/luac` and lots of `lua/*.o` files. Will it cause problems to add them to `.gitignore`?

**Comment by MockbaTheBorg** [comment]
It should not. Once RunCPM is built they should not be required anymore.
Can you give it a try and let me know?

**Comment by drawkula** [comment]
After addding targets and intermediate results to `.gitignore`:
```
RunCPM/RunCPM$ quiet make posix clean
RunCPM/RunCPM$ quiet make posix build
RunCPM/RunCPM$ ls RunCPM lua/lua{,c} # not listing the *.[ao] files
lua/lua  lua/luac  RunCPM
RunCPM/RunCPM$ git status
On branch master+more-gitignore
nothing to commit, working tree clean
```
This looks ok.
```
RunCPM$ tail -8 .gitignore 
# RunCPM targets and intermediate files
RunCPM/RunCPM
RunCPM/main.o

RunCPM/lua/*.o
RunCPM/lua/liblua.a
RunCPM/lua/lua
RunCPM/lua/luac
```
Ignoring all Lua stuff could have been a oneliner but I wanted to separate executables, libraries and the object files.

For other ports additions (`*.exe` and maybe more) will bee needed.

Keeping all built stuff in e.g. `build/$(SYS)` might even be better and will not need updating `.gitignore` when additional platforms, targets and intermediates show up.

**Comment by MockbaTheBorg** [comment]
I will take a look at this one and try to come up with a solution that cover all the bases. Will definitely use your suggestions.

**Comment by MockbaTheBorg** [comment]
I did a change to .gitignore ... I will close for now ... but then we can add more files if something appears.
