### ISSUE TITLE
RunCPM has an icon now...

### ISSUE THREAD

**Issue by drawkula** [MockbaTheBorg/RunCPM#67]
As seen in commit https://github.com/MockbaTheBorg/RunCPM/commit/492c868f03c685b0bf3a5ee0b3def5a73c2c01ad RunCPM has an icon now.

Maybe this is the moment to update [RunCPM's gallery at hackaday.io](https://hackaday.io/project/18291/gallery#d9f54f7a6ea5737b85f7d3f7dc2d7cd9)?

![20181110-093146-gmt--just_for_fun](https://user-images.githubusercontent.com/9768622/48300155-4c588400-e4d0-11e8-9639-5b6eb964b10d.png)
![20181110-095045-gmt--just_for_fun](https://user-images.githubusercontent.com/9768622/48300156-4c588400-e4d0-11e8-96eb-3f445e30e40c.png)

Okay... this Sixel stuff maybe is overshooting a bit but RunCPM's page(s) at hackaday.io might benefit from an update due to the added platform(s) and other improvements.

**Comment by drawkula** [comment]
> Hey, I want a sixel "howto"... :)

Good point too.
Let's add Sixel related stuff to issue https://github.com/MockbaTheBorg/RunCPM/issues/58 a.k.a. "[[FAQ?] Graphics? Yes we can!](https://github.com/MockbaTheBorg/RunCPM/issues/58)".

**Comment by MockbaTheBorg** [comment]
Did some update to the hackaday.io ... added new screenshots (showcasing the powerful icon), and extra references to the new ESP32 platform.
Other than that just pointed people here, as this is more updated source of information.
