### ISSUE TITLE
How to change clock speed of ESP32

### ISSUE THREAD

**Issue by vijayprakash1** [MockbaTheBorg/RunCPM#70]
Hi All,
I am trying to reduce the clock speed of my ESP32 module but it seems a bit difficult to change or somewhere I read we can't change the clock speed of the ESP32.
As my application is temperature sensitive and running on the battery so I thought by using lower clock speed I can achieve both.
Please let me know if anyone knows how to fix this issue.

**Comment by drawkula** [comment]
Unlike the ESP8266 which can change the speed with a simple function call, the ESP32 cannot do this with the current Arduino core (or ESP IDF).

----
Full thread:
—▷ https://github.com/espressif/arduino-esp32/issues/487

----
Shorter:
[Question](https://github.com/espressif/arduino-esp32/issues/487#issuecomment-313636924):
> does anybody know, if setting CPU clock at runtime, is even possible on the ESP32 (like it is on ESP8266)?

[Answer](https://github.com/espressif/arduino-esp32/issues/487#issuecomment-313638694):
> @everslick No, this isn't possible on the ESP32.

**Comment by vijayprakash1** [comment]
Ok, thanks @MockbaTheBorg will try to do this with other method

**Comment by vijayprakash1** [comment]
Is there any sample code on how to read a pin in ULP processor?

**Comment by drawkula** [comment]
I don't see documentation about Arduino/ESP32 ULP questions.
Maybe looking at the [ULP related issues of the Arduino/ESP32 core](https://github.com/espressif/arduino-esp32/issues?utf8=%E2%9C%93&q=is%3Aissue+ULP+) can help?
