### ISSUE TITLE
_findnext() in abstraction_arduino.h should populate 1st byte of returned directory entry with the file's user number

### ISSUE THREAD

**Issue by mecparts** [MockbaTheBorg/RunCPM#90]
I came across an oddity yesterday. I'd assembled SD.COM (Super Directory from SD137.LBR) and while it worked fine showing files in user area 0, it claimed that there were no files in any other user area. Some digging revealed that _findnext() was indeed finding files while in other user areas, but SD was tossing them.

The problem came down to SD testing the user number byte in the directory entry returned by _findnext(). In the original code, this was always set to zero. In my modified "search all user areas" version, I maintained the same functionality for regular searches and only populated the user number for my wildcarded user number searches. Since SD was using a regular find first/find next search, it would toss anything outside of user area zero.

Thinking about it, the user number should always be set in the directory entry returned by _findnext(). It's a directory entry, and directory entries have the user number in the first byte.

Here's the code fragment from the original:

```
if (match(fcbname, pattern)) {
   if (isdir) {
      _HostnameToFCB(dmaAddr, dirname);
      _RamWrite(dmaAddr, 0x00); <---- the offending line
   }
   _RamWrite(tmpFCB, filename[0] - '@');
   _HostnameToFCB(tmpFCB, dirname);
   result = 0x00;
   break;
}
```

and here's the modified version

```
if (match(fcbname, pattern)) {
   if (isdir) {
      _HostnameToFCB(dmaAddr, dirname);
      _RamWrite(dmaAddr, userCode); <-- the replacement line
   }
   _RamWrite(tmpFCB, filename[0] - '@');
   _HostnameToFCB(tmpFCB, dirname);
   result = 0x00;
   break;
}
```

There's a similar change needed in my modified code as well. This

```
_HostnameToFCB(dmaAddr, dirname);
if (allUsers) {
   DE->dr = currFindUser; // set user code for return
} else {
   DE->dr = userCode;
}
```
becomes this

```
_HostnameToFCB(dmaAddr, dirname);
if (allUsers) {
   DE->dr = currFindUser; // set user code for return
} else {               <---- added
   DE->dr = userCode;  <---- added
}
```

After making that change, SD works like a charm. My files have timestamps (using SdFat's builtin timestamp support, the Teensy4's RTC and a handful of new BDOS calls to mimic Z80DOS/NovaDOS's timestamp support) and now I can see 'em.

Wayne

**Comment by MockbaTheBorg** [comment]
I have added this change to all platforms. Will upload soon.
