### ISSUE TITLE
2 issues while compiling main.c on older linux-arm device (and solved)

### ISSUE THREAD

**Issue by guidol70** [MockbaTheBorg/RunCPM#95]
github doenst format this text fine - so as text attachment
[RunCPM_old_Linux.txt](https://github.com/MockbaTheBorg/RunCPM/files/3841187/RunCPM_old_Linux.txt)

**Comment by MockbaTheBorg** [comment]
Hi Guido,

I have added:
```
#ifndef POLLRDBAND
#define POLLRDBAND 0
#endif
#ifndef POLLRDNORM
#define POLLRDNORM 0
#endif
```
to the very end of posix.h. Right before the last #endif
This should make it build fine for this old platform as well as for any that do have these defined.

Thanks a lot,
Mockba the Borg

**Comment by guidol70** [comment]
this did work for the 2nd issue. but for the 1st issue I do need to add 
-stf=gnu99
to the compiler options

**Comment by MockbaTheBorg** [comment]
Yes.

As that one seems to be compiler specific I will leave as is.

What is this old platform you tried?
Getting things off the drawers huh?
:)

**Comment by guidol70** [comment]
Yes ist from the drawer, because here in Turkey I dont get not much new hardware :(
Its a Genesi Efika MX Smarttop: https://genesi.company/products/efika

**Comment by MockbaTheBorg** [comment]
Yeah, I know how it is. When I was in Brasil, back in the days, you had to either build your own computer or get some junk out from universities and such.
Cool ... you just made me want to go through the drawers (again) and see where else I can load RunCPM on.
:)
